version: "3.8"
services: 
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api.insecure=true"
            - "--providers.docker"
            - "--providers.docker.exposedByDefault=false"
        ports:
            # HTTP Port
            - "80:80"
            # Web UI
            - "8080:8080"
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
    account:
        build:
            context: ./account
            target: builder
        image: account
        expose:
            - "8080"
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.account.rule=Host(`calpal.test`) && PathPrefix(`/api/account`)"
        environment: 
            - ENV=dev
        volumes: 
            - ./account:/go/src/app
        command: reflex -r "\.go$$" -s -- sh -c "go run ./"