version: "3.8"
services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # HTTP Port
      - "80:80"
      # Web UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres-auth:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=***
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_auth:/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]
  account:
    build:
      context: ./account
      target: builder
    image: account
    env_file: .env.dev
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`calpal.test`) && PathPrefix(`/api/account`)"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
    depends_on:
      - postgres-auth
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
volumes:
  pgdata_auth:
