CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS tasks (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  userid uuid NOT NULL,
  email VARCHAR NOT NULL,
  task VARCHAR NOT NULL,
  ref_url VARCHAR NOT NULL DEFAULT '',
  email_reminder BOOLEAN DEFAULT FALSE,
  start_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  goal_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 day'
);